name: 🔄 Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black ruff pytest
        pip install -r requirements.txt
    
    - name: Run black formatting check
      run: black --check --diff .
    
    - name: Run ruff linting
      run: ruff check .
    
    - name: Run tests
      run: pytest tests/ -v
    
    - name: Test end-to-end generator
      run: |
        python generate.py --help
        echo "✅ Generator help command successful"

  build-demo:
    runs-on: ubuntu-latest
    needs: lint-and-format
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate demo page
      run: |
        if [ -f "generate.py" ]; then
          echo "🎯 Attempting to generate demo page..."
          timeout 60s python generate.py -n 1 --noise-level 1 || echo "⚠️ Demo generation failed or timed out"
        else
          echo "⚠️ generate.py not found, skipping demo generation"
        fi
    
    - name: Upload demo artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: demo-output
        path: |
          out/
          examples/